### PR TITLE
Exception when archiving file with size >4MB

### PR DESCRIPTION
**Pull request by IndusoftTeam**
…unt is greater than the number of elements from index to the end of the source collection

### CODE REVIEW

**Comment by IndusoftTeam** [comment]
Fix exeption offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection

**Comment by craftersmine** [comment]
Can you provide some additional info, when this happen? Like files to archive or archive to extract. I will probably approve and merge PR, but I just wanna see the issue by myself. Thanks.

**Comment by IndusoftTeam** [comment]
Create an archive file "data to reproduce the error.txt" 
[data to reproduce the error.txt](https://github.com/craftersmine/Asar.NET/files/12534445/data.to.reproduce.the.error.txt)

**Comment by IndusoftTeam** [comment]
Ошибка воспроизводится при создании архива в котором один из файлов имеет размер больше 4 мегабайт

**Comment by craftersmine** [comment]
Yeah, did able to reproduce it, but only when integrity calculation is enabled.

**Pull request merged**
